name: Deploy to DigitalOcean Droplet #comment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/mbsmrtic/repos/mandalavis
            git pull origin main
            cp index.html /var/www/html/index.html
            cp -r images/* /var/www/html/images
            cp -r static /var/www/html/static
            
