name: Deploy to DigitalOcean Droplet #comment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/mbsmrtic/repos/mandalavis
            git pull origin main
            cp *.* /var/www/mandalavis
            cd app
            cp *.* /var/www/mandalavis/app

            rm -rf /var/www/mandalavis/app/static/*
            cp -r static /var/www/mandalavis/app

            rm -rf /var/www/mandalavis/app/templates/*
            cp -r templates /var/www/mandalavis/app

            rm -rf /var/www/mandalavis/app/src/*
            cp -r src /var/www/mandalavis/app
            
